# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9175845ddddca1e212d03ac04fcd7ef115db64a2738c4c45f32a72b2668ea59ba6f8f91dda0768d67c4a95e3440604e8f3249b440ccc3423197d17578a1a921

test:
  secret_key_base: 450f4de16693ce53e5f42673560dd0729a275475b32c44f96a7f60e47894ba01b348fd371d463ca50df822abc9cfa237bd352f28d948f3b109d97e6384cc388d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
